### ISSUE TITLE
最近关注大佬的几个项目 做的和我好像有点相似

### ISSUE THREAD

**Issue by wwhai** [zgwit/iot-master-gateway#1]
【一定不是广告！！】这个是用go做的一个网关框架项目，大佬若是有兴趣可以一起搞搞   https://github.com/i4de/rulex

**Comment by zgwit** [comment]
我也一直在关注你的项目，最近略忙，有空仔细研究一下

**Comment by wwhai** [comment]
> 我也一直在关注你的项目，最近略忙，有空仔细研究一下

可加个好友交流一下

**Comment by zgwit** [comment]
怎么加你？

**Comment by wwhai** [comment]
> 怎么加你？
weixin：nilyouth
